version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:4.27
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 67776f6e30@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "8000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  web:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
volumes:
  db-data:
  pgadmin-data: