version: "3"
services:
  vue:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command:
      - bash
      - -c
      - |
        yarn install
        yarn run serve
